# Generated by Django 3.2.16 on 2022-12-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221205_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='num',
        ),
        migrations.RemoveField(
            model_name='change',
            name='code',
        ),
        migrations.AlterField(
            model_name='change',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.raw'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='num',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Routing',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
    ]
