# Generated by Django 3.2.16 on 2022-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221205_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='new_raw',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_raw',
            field=models.CharField(max_length=13),
        ),
    ]
