# Generated by Django 3.2.16 on 2022-12-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221206_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='old_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.raw'),
        ),
    ]
