# Generated by Django 3.2.16 on 2022-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_change_old_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='old_raw',
            field=models.CharField(max_length=13),
        ),
    ]
