# Generated by Django 3.2.16 on 2022-12-10 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_change_old_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='MK',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('num', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='raw',
            old_name='rtitle',
            new_name='layer',
        ),
        migrations.RenameField(
            model_name='raw',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='change',
            name='status',
        ),
        migrations.RemoveField(
            model_name='raw',
            name='id',
        ),
        migrations.AlterField(
            model_name='raw',
            name='num',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Sku_MK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mk_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mk')),
                ('sku_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sku')),
            ],
        ),
        migrations.AddField(
            model_name='mk',
            name='raw_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.raw'),
        ),
    ]
