# Generated by Django 3.2.16 on 2022-12-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_change_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw',
            old_name='num',
            new_name='layer',
        ),
        migrations.RenameField(
            model_name='raw',
            old_name='rtitle',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='raw',
            old_name='title',
            new_name='number',
        ),
        migrations.DeleteModel(
            name='Change',
        ),
    ]
