# Generated by Django 3.2.16 on 2022-12-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221210_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku_mk',
            name='mk_code',
        ),
        migrations.RemoveField(
            model_name='sku_mk',
            name='sku_num',
        ),
        migrations.DeleteModel(
            name='MK',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.DeleteModel(
            name='Sku_MK',
        ),
    ]
