# Generated by Django 3.2.16 on 2022-12-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221210_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='old_raw',
        ),
    ]
