# Generated by Django 3.2.16 on 2022-12-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221210_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw',
            old_name='number',
            new_name='num',
        ),
    ]
