# Generated by Django 3.2.16 on 2022-12-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_change_old_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change',
        ),
    ]
