# Generated by Django 3.2.16 on 2022-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_number_raw_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw',
            name='list',
        ),
        migrations.AddField(
            model_name='raw',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raw',
            name='layer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raw',
            name='num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
