# Generated by Django 3.2.16 on 2022-12-10 11:14

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='id',
            field=models.CharField(default=builtins.id, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raw',
            name='num',
            field=models.CharField(max_length=200),
        ),
    ]
