# Generated by Django 3.2.16 on 2022-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221210_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw',
            name='layer',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='raw',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='raw',
            name='num',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200),
        ),
    ]
