# Generated by Django 3.2.16 on 2022-12-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20221210_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raw',
        ),
    ]
