# Generated by Django 3.2.16 on 2022-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20221210_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw',
            name='layer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raw',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raw',
            name='num',
            field=models.CharField(max_length=200),
        ),
    ]
