# Generated by Django 3.2.16 on 2022-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20221212_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='photo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
