# Generated by Django 3.2.16 on 2022-12-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221214_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/pip'),
        ),
    ]
