# Generated by Django 3.2.16 on 2022-12-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_sku_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='raw_id',
            new_name='raw_current',
        ),
        migrations.AlterField(
            model_name='sku',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
