# Generated by Django 3.2.16 on 2022-12-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221218_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='raw_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_new', to='main.raw'),
        ),
        migrations.AlterField(
            model_name='change',
            name='raw_current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_current', to='main.raw'),
        ),
    ]
