# Generated by Django 3.2.16 on 2022-12-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20221220_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='number',
        ),
    ]
