# Generated by Django 3.2.16 on 2022-12-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_change_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='status',
        ),
    ]
